###
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
    "firstname": "Bruce",
    "lastname":"Wayne",
    "username": "ElBatman",
    "identification":"153453544",
    "password":"12344Batman",
    "active":true

}

###
GET http://localhost:9000/api/users HTTP/1.1

###
GET http://localhost:9000/api/users/6286d3b9e41e74e7b7eb90dc HTTP/1.1

###
PUT http://localhost:9000/api/users/6286d395e41e74e7b7eb90da HTTP/1.1
Content-Type: application/json

{
    "firstname": "Laurel",
    "lastname":"Lance",
    "username": "BlackCanary",
    "identification":"15376575544",
    "password":"12344Canary",
    "active":true
}


###
DELETE http://localhost:9000/api/users/6286d3b9e41e74e7b7eb90dc HTTP/1.1