###
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
    "firstname": "Bruce",
    "lastname":"Wayne",
    "username": "ElBatman",
    "identification":"153453544",
    "password":"12344Batman",
    "active":true

}

###
GET http://localhost:9000/api/users HTTP/1.1

###
GET http://localhost:9000/api/users/6286d3b9e41e74e7b7eb90dc HTTP/1.1

###
PUT http://localhost:9000/api/users/62869e5e303fe1ee60eb6700 HTTP/1.1
Content-Type: application/json

{
    "firstname": "Barry",
    "lastname":"Allen",
    "username": "MasVelozQueSuperman",
    "identification":"155777774",
    "password":"12344Flash",
    "active":true
}


###
DELETE http://localhost:9000/api/users/6286d3b9e41e74e7b7eb90dc HTTP/1.1