###

POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
  "firstname": "Clark",
    "lastname":"Kent",
    "username": "Superman",
    "identification":"1234476585",
    "password":"12344Superman",
    "active":true

}